name: Protected envs and stages

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]


jobs:
  deploy-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, acc, pro]
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: echo environment $PILLAR

      - name: Finish building
        run: echo "Build completed successfully"
