name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  deploy-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, acc, pro]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: echo environment ${{ vars.PILLAR }}

      - name: Finish building
        run: echo "Build completed successfully"
