name: Python CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install pytest
    - run: pytest exercise_2

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install black flake8
    - run: black --check .
      working-directory: exercise_2
    - run: flake8 .
      working-directory: exercise_2
