name: Hello World Workflow

on: 
  push:
    branches:
      - master


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/nightly_build
