name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  deploy:
    strategy:
      environment: [dev, acc, pro]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: echo environment $PILLAR

      - name: Finish building
        run: echo "Build completed successfully"
